---
# TODO
- name: "Create user {{ item }}"
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    create_home: true
    append: true
    groups: sudo
    password: "{{ item.password }}"
  loop: "{{ security_machine_admins }}"

- name: "Set {{ item }}'s authorized key"
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.ssh_pub_key_url }}"
  loop: "{{ security_machine_admins }}"

# TODO  Create separate sudoer file for each user
- name: Add configured user accounts to passwordless sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.username }}'
    line: '{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0644
  with_items: "{{ security_sudoers_passwordless }}"
  when: security_sudoers_passwordless | length > 0

- name: Add configured user accounts to passworded sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.username }}'
    line: '{{ item.username }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0644
  with_items: "{{ security_sudoers_passworded }}"
  when: security_sudoers_passworded | length > 0
